context: "corp"
source: "DC1"
projects:
  - name: "p1"
    consumers:
      - principal: "User:App0"
      - principal: "User:App1"
    streams:
      - principal: "User:App0"
        topics:
          read:
            - "inputA"
            - "inputB"
          write:
            - "outputA"
            - "outputB"
    connectors:
      - principal: "User:Connect1"
        connectors:
          - "jdbc-sink"
        topics:
          read:
            - "corp.dev.p1.connect-test"
    schemas:
      - principal: "User:App0"
        subjects:
          - "transactions"
      - principal: "User:App1"
        subjects:
          - "contracts"
    rbac:
      - ResourceOwner:
        - principal: "User:Foo"
      - SecurityAdmin:
        - principal: "User:Boo"
